package com.example.petstore.command.controller;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executors;
import java.util.concurrent.Semaphore;
import java.util.concurrent.atomic.AtomicInteger;

public class PetStoreLoadActualTester {

    // Target the actual @PostMapping endpoint in PetCommandController
    private static final String URL = "http://localhost:8081/pet";
    private static final int TOTAL_REQUESTS = 6000;
    private static final int CONCURRENCY_LIMIT = 500; 

    public static void main(String[] args) {
        System.out.println("🚀 Starting ACTUAL load test: POSTing " + TOTAL_REQUESTS + " pets...");
        
        try (var httpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
             var executor = Executors.newVirtualThreadPerTaskExecutor()) {

            Semaphore semaphore = new Semaphore(CONCURRENCY_LIMIT);
            AtomicInteger successCount = new AtomicInteger(0);
            AtomicInteger failureCount = new AtomicInteger(0);
            
            long startTime = System.currentTimeMillis();
            CompletableFuture<?>[] futures = new CompletableFuture[TOTAL_REQUESTS];

            for (int i = 0; i < TOTAL_REQUESTS; i++) {
                final int index = i;
                futures[i] = CompletableFuture.runAsync(() -> {
                    try {
                        semaphore.acquire();
                        
                        // Construct a JSON payload matching PetWriteEntity requirements
                        String jsonPayload = """
                            {
                                "name": "LoadTestPet_%d",
                                "category": { "id": 1 },
                                "photoUrl": "http://example.com/photo%d.jpg",
                                "status": "AVAILABLE",
                                "description": "Generated by load tester"
                            }
                            """.formatted(index, index);

                        HttpRequest request = HttpRequest.newBuilder()
                                .uri(URI.create(URL))
                                .header("Content-Type", "application/json")
                                .timeout(Duration.ofSeconds(10))
                                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload)) 
                                .build();

                        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

                        // Your controller returns ResponseEntity.ok (200)
                        if (response.statusCode() == 200 || response.statusCode() == 201) {
                            successCount.incrementAndGet();
                        } else {
                            failureCount.incrementAndGet();
                        }
                    } catch (Exception e) {
                        failureCount.incrementAndGet();
                    } finally {
                        semaphore.release();
                    }
                }, executor);
            }

            CompletableFuture.allOf(futures).join();

            long totalTime = System.currentTimeMillis() - startTime;
            printSummary(successCount.get(), failureCount.get(), totalTime);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void printSummary(int success, int failure, long time) {
        double seconds = time / 1000.0;
        System.out.println("\n--- 📊 Actual Load Test Results (POST) ---");
        System.out.println("Total Requests:  " + (success + failure));
        System.out.println("Successful:      " + success);
        System.out.println("Failed:          " + failure);
        System.out.println("Total Time:      " + time + "ms");
        if (seconds > 0) {
            System.out.printf("Avg Throughput:  %.2f req/sec%n", ((success + failure) / seconds));
        }
        System.out.println("------------------------------------------\n");
    }
}