
version: '3.9'

services:

  app1:
    build: ./app1
    ports:
      - "8880:8880"

  app2:
    build: ./app2
    ports:
      - "8881:8881"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - app1
      - app2
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env